global:
  environment: prd
  project: demo
  namespace: commons
  istiogateway: istio-system/http-gateway
  tag: dev-9d24fcd84-25012024-5
deployments:
  - name: demo
    replicaCount: 1
    containers:
      - name: demo
        image:
          name: 628510076340.dkr.ecr.ap-south-1.amazonaws.com/prd-demo
          pullPolicy: Always
        ports:
          - 8080
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 2000m
            memory: 2Gi
        secretName: demo
        configMapName: demo
        healthcheckPath: /actuator/health
        healthcheckPort: 8080
    secrets:
      secretManagerPath: /demo/k8s/prd/secrets
      secretStoreName: prd-secret-store
    services:
      ports:
        - servicePort: 443
          targetPort: 8080
          protocol: TCP
          name: port443
    ingress:
      enabled: true
      domainurl:
        - demo.go-yubi.com
      healthcheckPath: /
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
  
serviceaccount:
  name: demo-sa
  iamrole: arn:aws:iam::628510076340:role/prd-demo-eks-role-01
configmap:
  - name: demo
    data: 
      FLUENT_DESTINATION: newrelic
      FLUENT_LOKI_URL: https://dummy
      FLUENT_TAG: prd-demo
      FLUENT_LOKI_ENV: prd
      SERVICE_STARTUP: java -Dspring.profiles.active=prd -jar app.jar -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      http_proxy: http://proxy.dso.cadevops.net:3331
      https_proxy: http://proxy.dso.cadevops.net:3331
      no_proxy: 169.254.169.254,localhost,cadevops.net

externalsecret:
  enabled: true