- job-template: !include: build-image-java.tmpl

- project:
    name: build-api
    jobs:
      - "{folder}/self-serve-build-api":
          folder: "Yubi/NonPrd////demo"
          repo_name: otel
          branch: master
          environment:  # (dev,qa,uat,stg,uat-uae,prd-uae)
          service: demo
          namespace: 
          java_home: /usr/lib/jvm/jdk-21.0.2 # "/usr/lib/jvm/jdk-21.0.2"
          build_command: /opt/gradle-8.5/bin/gradle clean build
          jar_source: build/libs/demo-1.0.0-SNAPSHOT.jar # "build/libs/TemporalCodecService-1.0.0.jar"
          newrelic_source: "newrelic"
          deploy_job: "Yubi/NonPrd////demo/self-serve-deploy-app"
          repo_product:  # (colend, interop, pools, scf, platforms, loanos, common)
          repo_service: demo
          harbor_project:  # (yubi,yubi-mena)
